name: Update GCP Instance on Push to Master

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Secrets (for debugging)
        run: |
          echo "GCP_VM_IP: ${{ secrets.GCP_VM_IP }}"
          echo "GCP_VM_USERNAME: ${{ secrets.GCP_VM_USERNAME }}"
          # Avoid printing the actual SSH key for security reasons
          echo "GCP_VM_SSH_KEY is set: ${{ secrets.GCP_VM_SSH_KEY != '' }}"

      - name: Execute Script on GCP Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            updateapi
